services:
  ray-inference:
    container_name: ray-inference
    build:
      context: ./ray_inference
      dockerfile: Dockerfile
    image: daeun/ray-inference:cu116
    ports:
    - target: 8000
      published: '8000'
      protocol: tcp
      mode: ingress
    gpus:
    - count: -1
    shm_size: 8g
    healthcheck:
      test:
      - CMD
      - curl
      - -sf
      - http://127.0.0.1:8000/inference/healthz
      interval: 5s
      timeout: 2s
      retries: 60
      start_period: 30s
networks:
  default:
    name: hybrid-mlops-demo_default
